services:
  - type: web
    name: empiresguide-api
    env: node
    runtime: node
    buildCommand: |
      chmod +x prebuild.sh
      ./prebuild.sh
      npm install --no-optional
      chmod +x build.js
      node build.js
    startCommand: node render-index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: DATABASE
        value: mongodb+srv://tektrio2023:<PASSWORD>@age4.jx5tt.mongodb.net/?retryWrites=true&w=majority&appName=age4
        sync: false
      - key: DATABASE_PASSWORD
        value: EFsXKM83w4zMmkTJ
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SOCKET_TIMEOUT_MS
        value: 45000
      - key: SERVER_SELECTION_TIMEOUT_MS
        value: 10000
      - key: RETRY_WRITES
        value: true
      - key: USE_COMPLETE_MATCHUPS
        value: true
      - key: SKIP_PREFLIGHT_CHECK
        value: true
      - key: SKIP_TYPE_CHECK
        value: true
      - key: TS_NODE_TRANSPILE_ONLY
        value: true
      - key: MONGODB_TOLERANCE_MODE
        value: true
      - key: ALLOW_MOCK_DB_IN_PRODUCTION
        value: true
      - key: RENDER
        value: true
    healthCheckPath: /health/ping
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    # Definir limites de CPU e memória
    plan: free 