services:
  - type: web
    name: empiresguide-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # As variáveis abaixo devem ser configuradas no dashboard do Render como variáveis secretas
      # - key: MONGODB_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false
      - key: USE_COMPLETE_MATCHUPS
        value: false
    healthCheckPath: /api/ping 