services:
  - type: web
    name: empiresguide-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: USE_COMPLETE_MATCHUPS
        value: true
    healthCheckPath: /api/ping
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 