services:
  - type: web
    name: empiresguide-api
    env: node
    runtime: node
    buildCommand: |
      chmod +x prebuild.sh
      ./prebuild.sh
      npm install --no-optional
      chmod +x build.js
      node build.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: DATABASE
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: USE_COMPLETE_MATCHUPS
        value: true
      - key: SKIP_PREFLIGHT_CHECK
        value: true
      - key: SKIP_TYPE_CHECK
        value: true
      - key: TS_NODE_TRANSPILE_ONLY
        value: true
    healthCheckPath: /api/ping
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 